version: '3.8'

services:
  merchandise-service:
    build:
      context: ../
      dockerfile: src/OzonEdu.MerchandiseService/Dockerfile
    ports:
      - "8080:80"
      - "8083:443"
  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
  emailing-service :
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
  employees-service :
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
  supply-service :
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
  